export enum UserPatterns {
  CheckConnection = 'check_connection',
  CreateUser = 'create_user',
  GetUsers = 'get_users',
  GetUserById = 'get_user_by_id',
  GetUserByIdentifier = 'get_user_by_identifier',
  CreateUserStudent = 'create_user_student',
  CreateUserCoach = 'create_user_coach',
  RemoveUser = 'remove_user',
  FindOrCreate = 'find_or_create',
  SearchUser = 'search_user',
  UpdateUser = 'update_user',
  GetUserByMobile = 'get_user_by_mobile',
  GetUserByArgs = 'get_user_by_args',
  RemoveUsers = 'remove_users',
  GetUsersByIds = 'get_users_by_ids',
  VerifyMobile = 'verify_mobile',
}
