export enum BeltName {
  WHITE = 'سفید',
  YELLOW = 'زرد',
  GREEN = 'سبز',
  BLUE = 'آبی',
  RED = 'قرمز',
  POOM_1 = 'پوم 1',
  DAN_1 = 'دان 1',
  POOM_2 = 'پوم 2',
  DAN_2 = 'دان 2',
  POOM_3 = 'پوم 3',
  DAN_3 = 'دان 3',
  POOM_4 = 'پوم 4',
  DAN_4 = 'دان 4',
  DAN_5 = 'دان 5',
  DAN_6 = 'دان 6',
  DAN_7 = 'دان 7',
  DAN_8 = 'دان 8',
  DAN_9 = 'دان 9',
  DAN_10 = 'دان 10',
}
