export enum AttendanceMessages {
  CreatedAttendance = 'Attendance created successfully',
  UpdatedAttendance = 'Attendance updated successfully',
  NotFoundAttendance = 'Attendance not found',
  AlreadyExistsAttendanceWithUsername = 'A student with this username already exists',
  RemovedAttendanceSuccess = 'Attendance removed successfully',
  FailedToCreateAttendance = 'Failed to create attendance. Try again later',
  FailedToRemoveAttendance = 'Failed to remove attendance. Try again',
  InvalidAttendanceData = 'Invalid attendance data',
  UnauthorizedAction = 'You are not authorized',
  AttendanceUpdateSuccess = 'Attendance updated successfully',
  FailedToUpdateAttendance = 'Failed to update attendance. Try again',
  AttendanceListFetchError = 'Error fetching attendance list',
  DuplicateAttendanceEntry = 'This attendance is already registered',
  DuplicateNationalCode = 'A student with this national code already exists',
  FailedToUploadImage = 'Image upload failed. Try again',
  FailedToCreateUser = 'Failed to create user. Try again later',
  AttendanceNotFound = 'Attendance not found',
  UnauthorizedAttendances = 'These attendance IDs do not belong to this user',
  AttendanceNotBelongToUser = 'This attendance does not belong to the user',
  GetAttendanceSuccess = 'Attendance data retrieved successfully',
  AttendanceHasRelations = 'Cannot delete attendance relations with coaches or students',
  CannotRemoveMaleCoach = 'Cannot remove male gender while assigned coaches exist',
  CannotRemoveFemaleCoach = 'Cannot remove female gender while assigned coaches exist',
  CannotRemoveAttendanceAssignedToCoaches = 'The attendance has assigned coaches and cannot be removed',
  WalletDepletionUpdated = 'Wallet depletion status updated successfully',
}
