export enum CoachMessages {
  CreatedCoach = 'Coach created successfully',
  UpdatedCoach = 'Coach updated successfully',
  NotFoundCoach = 'Coach not found',
  AlreadyExistsCoachWithUsername = 'A coach with this username already exists',
  RemovedCoachSuccess = 'Coach removed successfully',
  FailedToCreateCoach = 'Failed to create coach. Try again later',
  FailedToRemoveCoach = 'Failed to remove coach. Try again',
  InvalidCoachData = 'Invalid coach data',
  UnauthorizedAction = 'You are not authorized',
  CoachUpdateSuccess = 'Coach updated successfully',
  FailedToUpdateCoach = 'Failed to update coach. Try again',
  CoachListFetchError = 'Error fetching coach list',
  DuplicateCoachEntry = 'This coach is already registered',
  DuplicateNationalCode = 'A coach with this national code already exists',
  FailedToUploadImage = 'Image upload failed. Try again',
  FailedToCreateUser = 'Failed to create user. Try again later',
  CoachNotFound = 'Coach not found',
  CoachNotBelongToUser = 'This coach does not belong to the user or club',
  GetCoachSuccess = 'Coach data retrieved successfully',
  CoachGenderMismatch = 'Coach gender mismatch. Invalid Club IDs:',
  CoachHasRelations = 'Cannot delete club relations with clubs or students',
  CoachHasStudents = 'Coach cannot be removed because they are assigned to students',
}
