export enum ClubMessages {
  CreatedClub = 'Club created successfully',
  UpdatedClub = 'Club updated successfully',
  NotFoundClub = 'Club not found',
  AlreadyExistsClubWithUsername = 'A student with this username already exists',
  RemovedClubSuccess = 'Club removed successfully',
  FailedToCreateClub = 'Failed to create club. Try again later',
  FailedToRemoveClub = 'Failed to remove club. Try again',
  InvalidClubData = 'Invalid club data',
  UnauthorizedAction = 'You are not authorized',
  ClubUpdateSuccess = 'Club updated successfully',
  FailedToUpdateClub = 'Failed to update club. Try again',
  ClubListFetchError = 'Error fetching club list',
  DuplicateClubEntry = 'This club is already registered',
  DuplicateNationalCode = 'A student with this national code already exists',
  FailedToUploadImage = 'Image upload failed. Try again',
  FailedToCreateUser = 'Failed to create user. Try again later',
  ClubNotFound = 'Club not found',
  UnauthorizedClubs = 'These club IDs do not belong to this user',
  ClubNotBelongToUser = 'This club does not belong to the user',
  GetClubSuccess = 'Club data retrieved successfully',
  ClubHasRelations = 'Cannot delete club relations with coaches or students',
  CannotRemoveMaleCoach = 'Cannot remove male gender while assigned coaches exist',
  CannotRemoveFemaleCoach = 'Cannot remove female gender while assigned coaches exist',
  CannotRemoveClubAssignedToCoaches = 'The club has assigned coaches and cannot be removed',
  WalletDepletionUpdated = 'Wallet depletion status updated successfully',
  CoachNotInClubs = 'Coach is not assigned to any club',
}
