export enum SessionMessages {
  CreatedSession = 'Session created successfully',
  UpdatedSession = 'Session updated successfully',
  NotFoundSession = 'Session not found',
  AlreadyExistsSessionWithUsername = 'A student with this username already exists',
  RemovedSessionSuccess = 'Session removed successfully',
  FailedToCreateSession = 'Failed to create session. Try again later',
  FailedToRemoveSession = 'Failed to remove session. Try again',
  InvalidSessionData = 'Invalid session data',
  UnauthorizedAction = 'You are not authorized',
  SessionUpdateSuccess = 'Session updated successfully',
  FailedToUpdateSession = 'Failed to update session. Try again',
  SessionListFetchError = 'Error fetching session list',
  DuplicateSessionEntry = 'This session is already registered',
  DuplicateNationalCode = 'A student with this national code already exists',
  FailedToUploadImage = 'Image upload failed. Try again',
  FailedToCreateUser = 'Failed to create user. Try again later',
  SessionNotFound = 'Session not found',
  UnauthorizedSessions = 'These session IDs do not belong to this user',
  SessionNotBelongToUser = 'This session does not belong to the user',
  GetSessionSuccess = 'Session data retrieved successfully',
  SessionHasRelations = 'Cannot delete session relations with coaches or students',
  CannotRemoveMaleCoach = 'Cannot remove male gender while assigned coaches exist',
  CannotRemoveFemaleCoach = 'Cannot remove female gender while assigned coaches exist',
  CannotRemoveSessionAssignedToCoaches = 'The session has assigned coaches and cannot be removed',
  WalletDepletionUpdated = 'Wallet depletion status updated successfully',
}
