export enum BeltMessages {
  CreatedBelt = 'Belt created successfully',
  UpdatedBelt = 'Belt updated successfully',
  NotFoundBelt = 'Belt not found',
  RemovedBeltSuccess = 'Belt removed successfully',
  FailedToCreateBelt = 'Failed to create belt. Try again later',
  FailedToRemoveBelt = 'Failed to remove belt. Try again',
  InvalidBeltData = 'Invalid belt data',
  BeltUpdateSuccess = 'Belt updated successfully',
  FailedToUpdateBelt = 'Failed to update belt. Try again',
  BeltListFetchError = 'Error fetching belt list',
  DuplicateBeltEntry = 'This belt is already registered',
  BeltNotFound = 'Belt not found',
  UnauthorizedBelts = 'These belt IDs do not belong to this user',
  BeltNotBelongToUser = 'This belt does not belong to the user',
  GetBeltSuccess = 'Belt data retrieved successfully',
  BeltHasRelations = 'Cannot delete belt relations with students',
  BeltNotFounds = 'Belts with IDs {ids} were not found',
}
