export enum Services {
  AUTH = 'AUTH_SERVICE',
  USER = 'USER_SERVICE',
  NOTIFICATION = 'NOTIFICATION_SERVICE',
  PAYMENT = 'PAYMENT_SERVICE',
  CLUB = 'CLUB_SERVICE',
  ACADEMY = 'ACADEMY_SERVICE',
}
