export enum Services {
  AUTH_USER = 'AUTH_USER_SERVICE',
  NOTIFICATION = 'NOTIFICATION_SERVICE',
  STUDENT = 'STUDENT_SERVICE',
  PAYMENT = 'PAYMENT_SERVICE',
  CLUB = 'CLUB_SERVICE',
  ACADEMY = 'ACADEMY_SERVICE',
}
