export enum AuthPatterns {
  CheckConnection = 'check_connection',
  Signup = 'signup',
  Signin = 'signin',
  Signout = 'signout',
  VerifyAccessToken = 'verify_access_token',
  RefreshToken = 'refresh_token',
  ForgetPassword = 'forget_password',
  ResetPassword = 'reset_password',
  VerifySignupOtp = 'verify_signup_otp',
  RequestNewOtp = 'request_new_otp',
  SigninStudent = 'signin_student',
  SigninCoach = 'signin_coach',
  SendOtp = 'send_otp',
  VerifyOtp = 'verify_otp',
}
