export enum AgeCategoryMessages {
  CreatedAgeCategory = 'Age Category created successfully',
  UpdatedAgeCategory = 'Age Category updated successfully',
  NotFoundAgeCategory = 'Age Category not found',
  RemovedAgeCategorySuccess = 'Age Category removed successfully',
  FailedToCreateAgeCategory = 'Failed to create age category. Try again later',
  FailedToRemoveAgeCategory = 'Failed to remove age category. Try again',
  InvalidAgeCategoryData = 'Invalid age category data',
  AgeCategoryUpdateSuccess = 'AgeCategory updated successfully',
  FailedToUpdateAgeCategory = 'Failed to update age category. Try again',
  AgeCategoryListFetchError = 'Error fetching age category list',
  DuplicateAgeCategoryEntry = 'This age category is already registered',
  AgeCategoryNotFound = 'Age Category not found',
  UnauthorizedAgeCategories = 'These age category IDs do not belong to this user',
  AgeCategoryNotBelongToUser = 'This age category does not belong to the user',
  GetAgeCategorySuccess = 'Age Category data retrieved successfully',
  AgeCategoryHasRelations = 'Cannot delete age category relations with students',
  AgeCategoryNotFounds = 'Age Categories with IDs {ids} were not found',
}
